# Generated by Django 4.2.11 on 2026-06-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0002_foodlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodlisting',
            name='location',
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='contact_phone',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='food_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='food_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='pickup_location',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Cooked', 'Cooked Food'), ('Dry', 'Dry Rations')], max_length=20),
        ),
    ]
