# Generated by Django 4.2.11 on 2026-06-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0003_remove_foodlisting_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
