# Generated by Django 4.2.11 on 2026-06-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0005_profile_contact_phone_profile_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_id', models.ForeignKey(db_column='food_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='food_api.foodlisting')),
            ],
        ),
    ]
