# Generated by Django 4.2.11 on 2026-06-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Donor', 'Donor'), ('Receiver', 'Receiver'), ('Organization', 'Organization'), ('Admin', 'Admin'), ('Rider', 'Rider')], default='Donor', max_length=20),
        ),
    ]
