# Generated by Django 4.2.11 on 2026-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0008_alter_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed / Awaiting Pickup'), ('Out for Delivery', 'Out for Delivery / In-Transit'), ('Completed', 'Successfully Completed')], default='Available', max_length=20),
        ),
    ]
