# Generated by Django 4.2.11 on 2026-08-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.TextField(blank=True, default=''),
        ),
    ]
