# Generated by Django 4.2.11 on 2026-09-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0011_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
