# Generated by Django 4.2.11 on 2026-09-05 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_api', '0012_foodlisting_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_food_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_food_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
