# Generated by Django 4.2.11 on 2026-09-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0013_foodlisting_claimed_by_foodlisting_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
