# Generated by Django 4.2.11 on 2026-09-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_api', '0014_alter_foodlisting_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
